export enum RoutePath {
  Splash = "/splash",
  Home = "/home",
  Auth = "/auth",
  SignupSuccess = "/auth/signup-success",
  Login = "/auth/login",
  Main = "/main",
  Chat = "/chat",
  ChatCreate = "/chat/create",
  Life = "/life",
  LifeDefail = "/life/detail",
  Community = "/community",
  CommunityWrite = "/community/write",
  CommunityDetail = "/community/detail",
  CommunityList = "/community/list",
  MyArticle = "/community/my-article",
  Diary = "/diary",
  DiaryDetail = "/diary/write",
  CreateDiary = "/diary/create/",
  More = "/more",
  MyInformation = "/more/my-information",
  ChangeNickname = "/more/change-nickname",
  ChangePassword = "/more/change-password",
  ChangeProfileImage = "/more/change-profile-image",
  Secession = "/more/secession",
  Etc = "/more/etc",
  Setting = "/more/setting",
}
