export enum RoutePath {
  Splash = "/splash",
  Home = "/home",
  Auth = "/auth",
  Main = "/main",
  Chat = "/chat",
  Life = "/life",
  LifeDefail = "/life/detail",
  Community = "/community",
  Diary = "/diary",
  DiaryDetail = "/diary/write",
  More = "/more",
  MyInformation = "/more/my-information",
  ChangeNickname = "/more/change-nickname",
  ChangePassword = "/more/change-password",
  ChangeProfileImage = "/more/change-profile-image",
  Secession = "/more/secession",
}
