name: sync up to codecommit

on:
  push:
    branches:
      - 'dev'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SSAKDUK_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SSAKDUK_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: aws-codecommit-sync 
        uses: afinkorea/aws-codecommit-sync@v1.0.0

        with:
          repository_name: ssakduk-client-frontend-test
          aws_region: ap-northeast-2
          branch: dev
